### ISSUE TITLE
How to use this theme?

### ISSUE THREAD

**Issue by michahell** [ryentzer/phpstorm-spacegray#1]
Just downloading and importing the .jar does not work. some instructions would be great :)

**Comment by ryentzer** [comment]
Hey, sorry about that. I just updated the readme for install on OS X. I'd imagine it would be a similar setup on other platforms.

**Comment by michahell** [comment]
Thanks! Though, I didn't have the `WebIde90` folder but i have a `WebStorm10` folder. pasting `Spacegray.icls` there and restarting didn't do anything. I could not select a theme in the colors & fonts section, and I've tried importing it but that gives an XML error. It neither is a theme, as I can only select default and Darcula :(

**Comment by ryentzer** [comment]
Was there not a `colors` directory inside of the `Webstorm10` folder?

**Comment by michahell** [comment]
Ah, yes, sorry, there was, I copied the `Spacegray.icls` file into that folder but that didn't seem to work. Is there anything I should check inside WebStorm? The colors dir does seem like it is the directory for other icls files as well, the Darcula theme sits there also.

**Comment by ryentzer** [comment]
If after a restart, it still does not show, then I'm not sure. Have you had any success with other theme files?

**Comment by michahell** [comment]
Hmm haven't tried any other theme files besides this one and the Darcula darker default theme, actually. Have a link to some other themes I could try? I'm thinking that since IntelliJ created separate editors (WebStorm, PhpStorm, etc.) the theme stuff got broken or different for each version. I tried some themes from http://www.ideacolorthemes.org/ but they all don't seem to work very well (either not, or bad)

**Comment by rhukster** [comment]
I have another SpaceGray theme and it works fine in PHPStorm 10, but this one does not.  I think there is some incompatibility that causes it not to show up in version 10.

**Comment by michahell** [comment]
Hello @rhukster ! Sorry for not updating this issue thread after my last comment, apparently it 'just works' in webstorm 10/11 at least, so no worries there :)

**Comment by rhukster** [comment]
Not working in phpstorm 10 though. Any ideas why?

**Comment by michahell** [comment]
Hmm unfortunately only a webstorm user here :/ I have a collegue who just a few days ago installed webstorm too, otherwise I would have asked him to try it out, so, sorry :/
